backend:
  name: git-gateway
  branch: master

media_folder: "/static/images"
public_folder: "images"

files:
  - name: "editing"
    label: "Editing"
    file: "/src/_data/editing.yml"
    description: "Books"
    fields:
      - {label: "Image", name: "image", widget: "image"}
