backend:
  name: git-gateway
  branch: master

media_folder: "/static/images"
public_folder: "images"


collections:
  - name: "work"
    label: "Work"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "editing"
        label: "Editing"
        file: "/src/data/editing.json"
        description: "Books"
        fields:
          - name: "editing"
            label: "Editing"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}