backend:
  name: git-gateway
  branch: master

media_folder: "/static/images"
public_folder: "images"


collections:
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "editing"
        label: "Editing"
        file: "/src/data/editing.yml"
        description: "Books"
        fields:
          - name: "editing1"
            label: "Editing1"
            widget: "object"
            fields:
              - {label: "Image", name: "image", widget: "image"}